//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loaddatfsh.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("loaddatfsh.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new bitmaps to the image.
        /// </summary>
        internal static string addBtn_ToolTip {
            get {
                return ResourceManager.GetString("addBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alpha # :.
        /// </summary>
        internal static string AlphaNumberText {
            get {
                return ResourceManager.GetString("AlphaNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitmap # :.
        /// </summary>
        internal static string BitmapNumberText {
            get {
                return ResourceManager.GetString("BitmapNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blend # :.
        /// </summary>
        internal static string BlendNumberText {
            get {
                return ResourceManager.GetString("BlendNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bitmap must be at least 128 x 128.
        /// </summary>
        internal static string CheckReplaceBitmapSizeError {
            get {
                return ResourceManager.GetString("CheckReplaceBitmapSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the loaded dat.
        /// </summary>
        internal static string closeDatBtn_ToolTip {
            get {
                return ResourceManager.GetString("closeDatBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress the items in the saved dat.
        /// </summary>
        internal static string compDatCb_ToolTip {
            get {
                return ResourceManager.GetString("compDatCb_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dat files (*.dat)|*.dat|All files (*.*)|*.*.
        /// </summary>
        internal static string DatFiles_Filter {
            get {
                return ResourceManager.GetString("DatFiles_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dat in Memory.
        /// </summary>
        internal static string DatInMemoryText {
            get {
                return ResourceManager.GetString("DatInMemoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of images in the loaded dat.
        /// </summary>
        internal static string datListView_ToolTip {
            get {
                return ResourceManager.GetString("datListView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the directory name for the selected image.
        /// </summary>
        internal static string dirTxt_ToolTip {
            get {
                return ResourceManager.GetString("dirTxt_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fsh files (*.fsh;*.qfs)|*.fsh;*.qfs|All files (*.*)|*.*.
        /// </summary>
        internal static string FshFiles_Filter {
            get {
                return ResourceManager.GetString("FshFiles_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fsh # .
        /// </summary>
        internal static string FshNumberText {
            get {
                return ResourceManager.GetString("FshNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the fsh type of the selected bitmap.
        /// </summary>
        internal static string fshTypeBox_ToolTip {
            get {
                return ResourceManager.GetString("fshTypeBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fshwrite compression when saving DXT1 and DXT3 fsh images.
        /// </summary>
        internal static string fshWriteCompCb_ToolTip {
            get {
                return ResourceManager.GetString("fshWriteCompCb_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A processor that supports SSE is required to use FshWrite compression..
        /// </summary>
        internal static string FshWriteSSERequired {
            get {
                return ResourceManager.GetString("FshWriteSSERequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new instance ids when saving into an existing dat.
        /// </summary>
        internal static string genNewInstCb_ToolTip {
            get {
                return ResourceManager.GetString("genNewInstCb_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap files (*.png;*.bmp)|*.png;*.bmp|All files (*.*)|*.*.
        /// </summary>
        internal static string ImageFiles_Filter {
            get {
                return ResourceManager.GetString("ImageFiles_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the end diget of the instance id.
        /// </summary>
        internal static string InstanceIDRadioButtons_ToolTip {
            get {
                return ResourceManager.GetString("InstanceIDRadioButtons_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid instance..
        /// </summary>
        internal static string InvalidInstanceFileNameFormat {
            get {
                return ResourceManager.GetString("InvalidInstanceFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance id &apos;{0}&apos; in instRange.txt contains invalid characters.
        ///It must only contain numbers 0-9 and letters A-F..
        /// </summary>
        internal static string InvalidInstanceIdFormat {
            get {
                return ResourceManager.GetString("InvalidInstanceIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance range in instRange.txt is not valid. 
        ///It must consist of the lower and upper texture range separated by a comma..
        /// </summary>
        internal static string InvalidInstanceRange {
            get {
                return ResourceManager.GetString("InvalidInstanceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a dat to modify its images.
        /// </summary>
        internal static string loadDatBtn_ToolTip {
            get {
                return ResourceManager.GetString("loadDatBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an existing fsh.
        /// </summary>
        internal static string loadFshBtn_ToolTip {
            get {
                return ResourceManager.GetString("loadFshBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading: .
        /// </summary>
        internal static string LoadingDatText {
            get {
                return ResourceManager.GetString("LoadingDatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new dat.
        /// </summary>
        internal static string newDatBtn_ToolTip {
            get {
                return ResourceManager.GetString("newDatBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new fsh.
        /// </summary>
        internal static string newFshBtn_ToolTip {
            get {
                return ResourceManager.GetString("newFshBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dat loaded.
        /// </summary>
        internal static string NoDatLoadedText {
            get {
                return ResourceManager.GetString("NoDatLoadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images loaded from {0}.
        /// </summary>
        internal static string NoImagesInDatFileError_Format {
            get {
                return ResourceManager.GetString("NoImagesInDatFileError_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected bitmap from the image.
        /// </summary>
        internal static string remBtn_ToolTip {
            get {
                return ResourceManager.GetString("remBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a Bitmap to replace the selected image..
        /// </summary>
        internal static string repBmp_NewFileSelect_Error {
            get {
                return ResourceManager.GetString("repBmp_NewFileSelect_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an image to replace..
        /// </summary>
        internal static string repBmp_NoImageSelected_Error {
            get {
                return ResourceManager.GetString("repBmp_NoImageSelected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the selected bitmap.
        /// </summary>
        internal static string repBtn_ToolTip {
            get {
                return ResourceManager.GetString("repBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alpha bitmap.
        /// </summary>
        internal static string SaveBitmap_Alpha_Suffix {
            get {
                return ResourceManager.GetString("SaveBitmap_Alpha_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitmap.
        /// </summary>
        internal static string SaveBitmap_Bitmap_Suffix {
            get {
                return ResourceManager.GetString("SaveBitmap_Bitmap_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blended bitmap.
        /// </summary>
        internal static string SaveBitmap_Blended_Suffix {
            get {
                return ResourceManager.GetString("SaveBitmap_Blended_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An image must be selected to save the {0}.
        /// </summary>
        internal static string SaveBitmap_Error_Format {
            get {
                return ResourceManager.GetString("SaveBitmap_Error_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a new or modified dat.
        /// </summary>
        internal static string saveDatBtn_ToolTip {
            get {
                return ResourceManager.GetString("saveDatBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the current Dat?.
        /// </summary>
        internal static string SaveDatChangesText {
            get {
                return ResourceManager.GetString("SaveDatChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current fsh.
        /// </summary>
        internal static string saveFshBtn_ToolTip {
            get {
                return ResourceManager.GetString("saveFshBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the current image?.
        /// </summary>
        internal static string SaveImageChangesText {
            get {
                return ResourceManager.GetString("SaveImageChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving:  .
        /// </summary>
        internal static string SavingDatText {
            get {
                return ResourceManager.GetString("SavingDatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReadyText {
            get {
                return ResourceManager.GetString("StatusReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the group id of the image.
        /// </summary>
        internal static string tgiGroupTxt_ToolTip {
            get {
                return ResourceManager.GetString("tgiGroupTxt_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the instance id of the image.
        /// </summary>
        internal static string tgiInstanceTxt_ToolTip {
            get {
                return ResourceManager.GetString("tgiInstanceTxt_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load settings:.
        /// </summary>
        internal static string UnableToLoadSettings {
            get {
                return ResourceManager.GetString("UnableToLoadSettings", resourceCulture);
            }
        }
    }
}
